#!/bin/bash
rm -r pages/*Abatron*
rm -r pages/*Autotest*
rm -r pages/BAS*
rm -r pages/Bat*
rm -r pages/Bgan*
rm -r pages/BGAN*
rm -r pages/Bne*
rm -r pages/BPS*
rm -r pages/BRE*
rm -r pages/*Cvs*
rm -r pages/Fpga*
rm -r pages/*HMAK*
rm -r pages/iShar*
rm -r pages/*JRC*
rm -r pages/KRA
rm -r pages/Msds*
rm -r pages/OSRMT*
rm -r pages/P\(2f\)AEH*
rm -r pages/P\(2f\)Agility*
rm -r pages/P\(2f\)Alpi*
rm -r pages/P\(2f\)AMAZ*
rm -r pages/P\(2f\)APPLILOG*
rm -r pages/P\(2f\)AV*
rm -r pages/P\(2f\)B*
rm -r pages/P\(2f\)Cargo*
rm -r pages/P\(2f\)CARGO*
rm -r pages/P\(2f\)CATER*
rm -r pages/P\(2f\)Chang*
rm -r pages/P\(2f\)CHR*
rm -r pages/P\(2f\)CLA*
rm -r pages/P\(2f\)Coyote*
rm -r pages/P\(2f\)DHL*
rm -r pages/P\(2f\)DSV*
rm -r pages/P\(2f\)E*
rm -r pages/P\(2f\)EMS*
rm -r pages/P\(2f\)Erfolg
rm -r pages/P\(2f\)FUR*
rm -r pages/P\(2f\)GGL*
rm -r pages/P\(2f\)GH\(2f\)BNE*
rm -r pages/P\(2f\)GH\(2f\)BPS*
rm -r pages/P\(2f\)GH\(2f\)BSDR*
rm -r pages/P\(2f\)GH\(2f\)C3I*
rm -r pages/P\(2f\)GH\(2f\)COOP*
rm -r pages/P\(2f\)GH\(2f\)DS*
rm -r pages/P\(2f\)GH\(2f\)FREX*
rm -r pages/P\(2f\)GH\(2f\)GANE*
rm -r pages/P\(2f\)GH\(2f\)GHT*
rm -r pages/P\(2f\)GH\(2f\)GW*
rm -r pages/P\(2f\)GH\(2f\)NAGELDK*
rm -r pages/P\(2f\)GH\(2f\)NO*
rm -r pages/P\(2f\)GH\(2f\)SDR*
rm -r pages/P\(2f\)GH\(2f\)TCM*
rm -r pages/P\(2f\)GH\(2f\)TDX*
rm -r pages/P\(2f\)GMV*
rm -r pages/P\(2f\)GoodYear*
rm -r pages/P\(2f\)GT*
rm -r pages/P\(2f\)GW*
rm -r pages/P\(2f\)GX*
rm -r pages/P\(2f\)Hei*
rm -r pages/P\(2f\)HNS*
rm -r pages/P\(2f\)HSG*
rm -r pages/P\(2f\)IAS*
rm -r pages/P\(2f\)INM*
rm -r pages/P\(2f\)JYSK*
rm -r pages/P\(2f\)Lidl*
rm -r pages/P\(2f\)LIDL*
rm -r pages/P\(2f\)LO*
rm -r pages/P\(2f\)MAGE*
rm -r pages/P\(2f\)MAGN*
rm -r pages/P\(2f\)NAG*
rm -r pages/P\(2f\)Nage*
rm -r pages/P\(2f\)OMN*
rm -r pages/P\(2f\)PEMA*
rm -r pages/P\(2f\)POFERRY*
rm -r pages/P\(2f\)POLA*
rm -r pages/P\(2f\)PORTMANN*
rm -r pages/P\(2f\)PTV*
rm -r pages/P\(2f\)QU*
rm -r pages/P\(2f\)RDE*
rm -r pages/P\(2f\)RE*
rm -r pages/P\(2f\)ROC*
rm -r pages/P\(2f\)SAP*
rm -r pages/P\(2f\)SAV*
rm -r pages/P\(2f\)SCH*
rm -r pages/P\(2f\)Senn*
rm -r pages/P\(2f\)TEVEX*
rm -r pages/P\(2f\)THAL*
rm -r pages/P\(2f\)TOPL*
rm -r pages/P\(2f\)TRANS*
rm -r pages/P\(2f\)VIA*
rm -r pages/P\(2f\)WKT*
rm -r pages/ptv*
rm -r pages/Rasmus*
rm -r pages/*Satcom*
rm -r pages/*SatCom*
rm -r pages/Sdm*
rm -r pages/Shorts*
rm -r pages/Spot*
rm -r pages/*Student*
rm -r pages/*TestCentre*
