#!/bin/bash
rm -r pages/ABA
rm -r pages/Abbreviation
rm -r pages/*Abatron*
rm -r pages/*Autotest*
rm -r pages/Api*
rm -r pages/File*
rm -r pages/Eclipse*
rm -r pages/BAS*
rm -r pages/Bat*
rm -r pages/Bgan*
rm -r pages/BGAN*
rm -r pages/Bne*
rm -r pages/BNE*
rm -r pages/Baf*
rm -r pages/I4*
rm -r pages/Hns*
rm -r pages/Hal*
rm -r pages/GhDis*
rm -r pages/Iai*
rm -r pages/InstallSphinx*
rm -r pages/InstallV*
rm -r pages/BPLT*
rm -r pages/Bplt*
rm -r pages/*Bgan*
rm -r pages/BPS*
rm -r pages/BRE*
rm -r pages/*Cvs*
rm -r pages/Fpga*
rm -r pages/*HMAK*
rm -r pages/iShar*
rm -r pages/*JRC*
rm -r pages/KRA
rm -r pages/KRG
rm -r pages/LAC
rm -r pages/MAL
rm -r pages/MIW
rm -r pages/OLM*
rm -r pages/Phy*
rm -r pages/RTR
rm -r pages/Sbsa*
rm -r pages/Senti*
rm -r pages/Sgm
rm -r pages/Squa*
rm -r pages/Teclo
rm -r pages/Terra*
rm -r pages/TestUSIM
rm -r pages/Undocumented*
rm -r pages/Universi*
rm -r pages/USIM
rm -r pages/MergingA*
rm -r pages/Msds*
rm -r pages/OSRMT*
rm -r pages/P\(2f\)AEH*
rm -r pages/P\(2f\)Agility*
rm -r pages/P\(2f\)Alpi*
rm -r pages/P\(2f\)AMAZ*
rm -r pages/P\(2f\)APPLILOG*
rm -r pages/P\(2f\)AV*
rm -r pages/P\(2f\)B*
rm -r pages/P\(2f\)Cargo*
rm -r pages/P\(2f\)CARGO*
rm -r pages/P\(2f\)CATER*
rm -r pages/P\(2f\)Chang*
rm -r pages/P\(2f\)CHR*
rm -r pages/P\(2f\)CLA*
rm -r pages/P\(2f\)Coyote*
rm -r pages/P\(2f\)DHL*
rm -r pages/P\(2f\)DSV*
rm -r pages/P\(2f\)E*
rm -r pages/*EMS*
rm -r pages/P\(2f\)Erfolg
rm -r pages/P\(2f\)FUR*
rm -r pages/P\(2f\)GGL*
rm -r pages/P\(2f\)GH\(2f\)BNE*
rm -r pages/P\(2f\)GH\(2f\)BPS*
rm -r pages/P\(2f\)GH\(2f\)BSDR*
rm -r pages/P\(2f\)GH\(2f\)C3I*
rm -r pages/P\(2f\)GH\(2f\)COOP*
rm -r pages/P\(2f\)GH\(2f\)DS*
rm -r pages/P\(2f\)GH\(2f\)FREX*
rm -r pages/P\(2f\)GH\(2f\)GANE*
rm -r pages/P\(2f\)GH\(2f\)GHT*
rm -r pages/P\(2f\)GH\(2f\)GW*
rm -r pages/P\(2f\)GH\(2f\)NAGELDK*
rm -r pages/P\(2f\)GH\(2f\)NO*
rm -r pages/P\(2f\)GH\(2f\)SDR*
rm -r pages/P\(2f\)GH\(2f\)TCM*
rm -r pages/P\(2f\)GH\(2f\)TDX*
rm -r pages/P\(2f\)GMV*
rm -r pages/P\(2f\)GoodYear*
rm -r pages/P\(2f\)GT*
rm -r pages/P\(2f\)GW*
rm -r pages/P\(2f\)GX*
rm -r pages/P\(2f\)Hei*
rm -r pages/P\(2f\)HNS*
rm -r pages/P\(2f\)HSG*
rm -r pages/P\(2f\)IAS*
rm -r pages/P\(2f\)INM*
rm -r pages/P\(2f\)JYSK*
rm -r pages/P\(2f\)Lidl*
rm -r pages/P\(2f\)LIDL*
rm -r pages/P\(2f\)LO*
rm -r pages/P\(2f\)MAGE*
rm -r pages/P\(2f\)MAGN*
rm -r pages/P\(2f\)NAG*
rm -r pages/P\(2f\)Nage*
rm -r pages/P\(2f\)OMN*
rm -r pages/P\(2f\)PEMA*
rm -r pages/P\(2f\)POFERRY*
rm -r pages/P\(2f\)POLA*
rm -r pages/P\(2f\)PORTMANN*
rm -r pages/P\(2f\)PTV*
rm -r pages/P\(2f\)QU*
rm -r pages/P\(2f\)RDE*
rm -r pages/P\(2f\)RE*
rm -r pages/P\(2f\)ROC*
rm -r pages/P\(2f\)SAP*
rm -r pages/P\(2f\)SAV*
rm -r pages/P\(2f\)SCH*
rm -r pages/P\(2f\)Senn*
rm -r pages/P\(2f\)TEVEX*
rm -r pages/P\(2f\)THAL*
rm -r pages/P\(2f\)TOPL*
rm -r pages/P\(2f\)TRANS*
rm -r pages/P\(2f\)VIA*
rm -r pages/P\(2f\)WKT*
rm -r pages/ptv*
rm -r pages/Rasmus*
rm -r pages/*Satcom*
rm -r pages/*SatCom*
rm -r pages/Sdm*
rm -r pages/Shorts*
rm -r pages/Spot*
rm -r pages/*Student*
rm -r pages/*TestCentre*
rm -r pages/*Sprint_Review*
rm -r pages/*Recurring_tasks*
rm -r pages/Local*
rm -r pages/Green*
rm -r pages/*Milestone*
rm -r pages/*MileStone*
rm -r pages/ITIL*
rm -r pages/Model*
rm -r pages/cvst*
rm -r pages/New*
rm -r pages/Inmar*
rm -r pages/Bolds*
rm -r pages/ETSI*
rm -r pages/*ETI*
rm -r pages/freja*
rm -r pages/JNJ
rm -r pages/Moin*
rm -r pages/Net2000*
rm -r pages/*VxWorks*
rm -r pages/Current*Work*List
rm -r pages/Wiki*
rm -r pages/BadContent
rm -r pages/dsv*
